### ISSUE TITLE
I have this error while running.

### ISSUE THREAD

**Issue by Aithusa1113** [kunalrdeshmukh/Image_Compression#1]
File "encoder.py", line 39, in <module>
    model = model.cuda()
AttributeError: 'collections.OrderedDict' object has no attribute 'cuda'

**Comment by kunalrdeshmukh** [comment]
Thanks for trying it our. Please pull the latest code now. 
Earlier I had called `state_dict()` on model before saving it in order to save some space. Now I have saved a final model as pickle object. - 
`  save(encoder,'%s/Encoder_model.pth'%opt.outf )`
  `save(decoder,'%s/Decoder_model.pth'%opt.outf ) `

I will add an option to load model at specific epoch in few days. 

Please be aware that this project is still at very early stages of development.
